name: Test ARC Runner

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # позволяет запускать вручную из UI

jobs:
  test-job:
    runs-on: arc-runner-set  # ← это имя твоего RunnerScaleSet
    steps:
      - name: Say hello
        run: echo "Hello from my self-hosted runnerrr!"

      - name: Show runner info
        run: |
          echo "Hostname: $(hostname)"
          echo "Whoami: $(whoami)"
          echo "Kernel: $(uname -r)"

      - name: Sleep a bit (чтобы успеть посмотреть под)
        run: sleep 100

      - name: Done
        run: echo "Job complete, pod will be deleted"
